name: Dispatch continuous fuzzing

on:
  push:
    branches: [main]

permissions:                                                                                                                                                                                                                          
    contents: read

jobs:
  upload:
    runs-on: ubuntu-latest
    environment: fuzz
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - run: rustup update nightly
      - run: rustup default nightly
      
      - uses: dtolnay/install@d0dc46e85ffd2c174b5ac0489e17f95dae84fa5a # cargo-fuzz
      - run: cargo +nightly fuzz build --no-trace-compares

      - name: Prepare bundle
        run: ./fuzz/build-fuzz-bundle.sh

      - name: Upload bundle to FuzzCorp
        uses: asymmetric-research/fuzz-upload-action@1140f6fc0fc9c59aa66f3a705c55c93f260f715b # v1.0.4
        with:
          upload_type: bundle
          upload_path: ./fuzz/target/bundle
        env:
          FUZZ_API_ORIGIN: ${{ secrets.FUZZ_API_ORIGIN }}
          FUZZ_ORGANIZATION: anza
          FUZZ_PROJECT: sbpf
          FUZZ_USER: ${{ secrets.FUZZ_USER }}
          FUZZ_PASSWORD: ${{ secrets.FUZZ_PASSWORD }}